import equipmentData from '../data/octopath_traveler_1/equipment.json'
import skillData from '../data/octopath_traveler_1/skills.json'

export const Travelers = [
	{
		name: "Ophilia Clement",
		slug: "ophilia",
		full_image: '/images/full/octopath_traveler_1/ophilia.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/ophilia/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/ophilia/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/ophilia/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/ophilia/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/ophilia/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/ophilia/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/ophilia/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/ophilia/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/ophilia/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/ophilia/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/ophilia/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
			Arcanist: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
			Conjurer: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
			Inventor: "/images/sprites/octopath_traveler_1/ophilia/cleric.png",
		},
		primary_job: "Cleric",
		secondary_job: "None",
		active: "staff",
		equipped: {
			weapons: {
				staff: equipmentData.weapons.staves[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Cyrus Albirght",
		slug: "cyrus",
		full_image: '/images/full/octopath_traveler_1/cyrus.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/cyrus/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/cyrus/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/cyrus/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/cyrus/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/cyrus/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/cyrus/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/cyrus/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/cyrus/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/cyrus/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/cyrus/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/cyrus/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
			Arcanist: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
			Conjurer: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
			Inventor: "/images/sprites/octopath_traveler_1/cyrus/scholar.png",
		},
		primary_job: "Scholar",
		secondary_job: "None",
		active: "staff",
		equipped: {
			weapons: {
				staff: equipmentData.weapons.staves[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Tressa Colzione",
		slug: "tressa",
		full_image: '/images/full/octopath_traveler_1/tressa.png',
		primary_job: "Merchant",
		secondary_job: "None",
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/tressa/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/tressa/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/tressa/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/tressa/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/tressa/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/tressa/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/tressa/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/tressa/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/tressa/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/tressa/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/tressa/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
			Arcanist: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
			Conjurer: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
			Inventor: "/images/sprites/octopath_traveler_1/tressa/merchant.png",
		},
		active: "polearm",
		equipped: {
			weapons: {
				polearm: equipmentData.weapons.polearms[0],
				bow: equipmentData.weapons.bows[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Olberic Eisenberg",
		slug: "olberic",
		full_image: '/images/full/octopath_traveler_1/olberic.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/olberic/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/olberic/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/olberic/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/olberic/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/olberic/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/olberic/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/olberic/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/olberic/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/olberic/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/olberic/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/olberic/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
			Arcanist: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
			Conjurer: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
			Inventor: "/images/sprites/octopath_traveler_1/olberic/warrior.png",
		},
		primary_job: "Warrior",
		secondary_job: "None",
		active: "sword",
		equipped: {
			weapons: {
				sword: equipmentData.weapons.swords[0],
				polearm: equipmentData.weapons.polearms[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Primrose Azelhart",
		slug: "primrose",
		full_image: '/images/full/octopath_traveler_1/primrose.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/primrose/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/primrose/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/primrose/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/primrose/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/primrose/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/primrose/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/primrose/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/primrose/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/primrose/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/primrose/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/primrose/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
			Arcanist: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
			Conjurer: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
			Inventor: "/images/sprites/octopath_traveler_1/primrose/dancer.png",
		},
		primary_job: "Dancer",
		secondary_job: "None",
		active: "dagger",
		equipped: {
			weapons: {
				dagger: equipmentData.weapons.daggers[0],
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Alfynn Greengrass",
		slug: "alfynn",
		full_image: '/images/full/octopath_traveler_1/alfynn.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/alfynn/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/alfynn/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/alfynn/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/alfynn/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/alfynn/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/alfynn/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/alfynn/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/alfynn/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/alfynn/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/alfynn/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/alfynn/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/alfynn/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/alfynn/apothecary.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/alfynn/apothecary.png",
			Arcanist: "/images/sprites/octopath_traveler_1/alfynn/apothecary.png",
			Conjurer: "/Noneimages/sprites/octopath_traveler_1/alfynn/apothecary.png",
			Inventor: "/images/sprites/octopath_traveler_1/alfynn/apothecary.png",
		},
		primary_job: "Apothecary",
		secondary_job: "None",
		active: "axe",
		equipped: {
			weapons: {
				axe: equipmentData.weapons.axes[0],
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Therion",
		slug: "therion",
		full_image: '/images/full/octopath_traveler_1/therion.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/therion/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/therion/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/therion/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/therion/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/therion/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/therion/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/therion/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/therion/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/therion/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/therion/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/therion/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/therion/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/therion/thief.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/therion/thief.png",
			Arcanist: "/images/sprites/octopath_traveler_1/therion/thief.png",
			Conjurer: "/images/sprites/octopath_traveler_1/therion/thief.png",
			Inventor: "/images/sprites/octopath_traveler_1/therion/thief.png",
		},
		primary_job: "Thief",
		secondary_job: "None",
		active: "dagger",
		equipped: {
			weapons: {
				sword: equipmentData.weapons.swords[0],
				dagger: equipmentData.weapons.daggers[0],
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "H'aanit",
		slug: "h'aanit",
		full_image: '/images/full/octopath_traveler_1/haanit.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_1/haanit/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_1/haanit/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_1/haanit/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_1/haanit/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_1/haanit/scholar.png",
			Thief: "/images/sprites/octopath_traveler_1/haanit/thief.png",
			Warrior: "/images/sprites/octopath_traveler_1/haanit/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_1/haanit/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_1/haanit/sorcerer.png",
			Starseer: "/images/sprites/octopath_traveler_1/haanit/starseer.png",
			Warmaster: "/images/sprites/octopath_traveler_1/haanit/warmaster.png",
			None: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
			Armsmaster: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
			Arcanist: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
			Conjurer: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
			Inventor: "/images/sprites/octopath_traveler_1/haanit/hunter.png",
		},
		primary_job: "Hunter",
		secondary_job: "None",
		active: "bow",
		equipped: {
			weapons: {
				axe: equipmentData.weapons.axes[0],
				bow: equipmentData.weapons.bows[0],
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
]
