import equipmentData from '../data/octopath_traveler_1/equipment.json'
import skillData from '../data/octopath_traveler_1/skills.json'

export const Travelers = [
	{
		name: "Ochette",
		slug: "ochette",
		full_image: '/images/full/octopath_traveler_2/ochette.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/ochette/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/ochette/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/ochette/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/ochette/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/ochette/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/ochette/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/ochette/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/ochette/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/ochette/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/ochette/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/ochette/inventor.png",
			None: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
			Runelord: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
			Starseer: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
			Warmaster: "/images/sprites/octopath_traveler_2/ochette/hunter.png",
		},
		active: "bow",
		primary_job: "Hunter",
		secondary_job: "None",
		equipped: {
			weapons: {
				axe: equipmentData.weapons.axes[0],
				bow: equipmentData.weapons.bows[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Castti Florenz",
		slug: "castti",
		full_image: '/images/full/octopath_traveler_2/castti.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/castti/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/castti/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/castti/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/castti/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/castti/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/castti/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/castti/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/castti/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/castti/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/castti/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/castti/inventor.png",
			None: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
			Runelord: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
			Starseer: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
			Warmaster: "/images/sprites/octopath_traveler_2/castti/apothecary.png",
		},
		active: "axe",
		primary_job: "Apothecary",
		secondary_job: "None",
		equipped: {
			weapons: {
				axe: equipmentData.weapons.axes[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Throne Anguis",
		slug: "throne",
		full_image: '/images/full/octopath_traveler_2/throne.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/throne/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/throne/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/throne/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/throne/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/throne/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/throne/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/throne/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/throne/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/throne/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/throne/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/throne/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/throne/inventor.png",
			None: "/images/sprites/octopath_traveler_2/throne/thief.png",
			Runelord: "/images/sprites/octopath_traveler_2/throne/thief.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/throne/thief.png",
			Starseer: "/images/sprites/octopath_traveler_2/throne/thief.png",
			Warmaster: "/images/sprites/octopath_traveler_2/throne/thief.png",
		},
		active: "dagger",
		primary_job: "Thief",
		secondary_job: "None",
		equipped: {
			weapons: {
				sword: equipmentData.weapons.swords[0],
				dagger: equipmentData.weapons.daggers[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Osvald V. Vanstein",
		slug: "osvald",
		full_image: '/images/full/octopath_traveler_2/osvald.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/osvald/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/osvald/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/osvald/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/osvald/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/osvald/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/osvald/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/osvald/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/osvald/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/osvald/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/osvald/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/osvald/inventor.png",
			None: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
			Runelord: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
			Starseer: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
			Warmaster: "/images/sprites/octopath_traveler_2/osvald/scholar.png",
		},
		active: "staff",
		primary_job: "Scholar",
		secondary_job: "None",
		equipped: {
			weapons: {
				staff: equipmentData.weapons.staves[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Partitio Yellowil",
		slug: "partitio",
		full_image: '/images/full/octopath_traveler_2/partitio.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/partitio/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/partitio/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/partitio/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/partitio/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/partitio/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/partitio/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/partitio/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/partitio/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/partitio/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/partitio/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/partitio/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/partitio/inventor.png",
			None: "/images/sprites/octopath_traveler_2/partitio/merchant.png",
			Runelord: "/images/sprites/octopath_traveler_2/partitio/runelord.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/partitio/merchant.png",
			Starseer: "/images/sprites/octopath_traveler_2/partitio/merchant.png",
			Warmaster: "/images/sprites/octopath_traveler_2/partitio/merchant.png",
		},
		active: "polearm",
		primary_job: "Merchant",
		secondary_job: "None",
		equipped: {
			weapons: {
				polearm: equipmentData.weapons.polearms[0],
				bow: equipmentData.weapons.bows[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Agnea Bristarni",
		slug: "agnea",
		full_image: '/images/full/octopath_traveler_2/agnea.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/agnea/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/agnea/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/agnea/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/agnea/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/agnea/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/agnea/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/agnea/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/agnea/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/agnea/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/agnea/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/agnea/inventor.png",
			None: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
			Runelord: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
			Starseer: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
			Warmaster: "/images/sprites/octopath_traveler_2/agnea/dancer.png",
		},
		active: "dagger",
		primary_job: "Dancer",
		secondary_job: "None",
		equipped: {
			weapons: {
				dagger: equipmentData.weapons.daggers[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Temenos Mistral",
		slug: "temenos",
		full_image: '/images/full/octopath_traveler_2/temenos.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/temenos/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/temenos/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/temenos/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/temenos/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/temenos/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/temenos/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/temenos/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/temenos/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/temenos/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/temenos/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/temenos/inventor.png",
			None: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
			Runelord: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
			Starseer: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
			Warmaster: "/images/sprites/octopath_traveler_2/temenos/cleric.png",
		},
		active: "staff",
		primary_job: "Cleric",
		secondary_job: "None",
		equipped: {
			weapons: {
				staff: equipmentData.weapons.staves[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
	{
		name: "Hikari Ku",
		slug: "hikari",
		full_image: '/images/full/octopath_traveler_2/hikari.png',
		sprites: {
			Apothecary: "/images/sprites/octopath_traveler_2/hikari/apothecary.png",
			Cleric: "/images/sprites/octopath_traveler_2/hikari/cleric.png",
			Dancer: "/images/sprites/octopath_traveler_2/hikari/dancer.png",
			Hunter: "/images/sprites/octopath_traveler_2/hikari/hunter.png",
			Merchant: "/images/sprites/octopath_traveler_2/hikari/merchant.png",
			Scholar: "/images/sprites/octopath_traveler_2/hikari/scholar.png",
			Thief: "/images/sprites/octopath_traveler_2/hikari/thief.png",
			Warrior: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
			Armsmaster: "/images/sprites/octopath_traveler_2/hikari/armsmaster.png",
			Arcanist: "/images/sprites/octopath_traveler_2/hikari/arcanist.png",
			Conjurer: "/images/sprites/octopath_traveler_2/hikari/conjurer.png",
			Inventor: "/images/sprites/octopath_traveler_2/hikari/inventor.png",
			None: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
			Runelord: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
			Sorcerer: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
			Starseer: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
			Warmaster: "/images/sprites/octopath_traveler_2/hikari/warrior.png",
		},
		active: "sword",
		primary_job: "Warrior",
		secondary_job: "None",
		equipped: {
			weapons: {
				sword: equipmentData.weapons.swords[0],
				polearm: equipmentData.weapons.polearms[0]
			},
			shield: equipmentData.shields[0],
			headgear: equipmentData.headgears[0],
			body_armor: equipmentData.body_armors[0],
			accessory_1: equipmentData.accessories[0],
			accessory_2: equipmentData.accessories[0],
			supportSkill1: skillData.support_skills[0],
			supportSkill2: skillData.support_skills[0],
			supportSkill3: skillData.support_skills[0],
			supportSkill4: skillData.support_skills[0],
		}
	},
]
